import type { Lead } from "./leads";

/**
 * Client-side PDF export of a lead/buyer profile (jsPDF, dynamically imported).
 * Produces a clean, text-based dossier grouped exactly like the on-screen one.
 */

const GROUPS: { title: string; fields: [keyof Lead, string][] }[] = [
  {
    title: "Contact",
    fields: [
      ["full_name", "Full Name"],
      ["designation", "Designation"],
      ["email", "Email"],
      ["phone", "Phone"],
      ["website", "Website"],
      ["source", "Source"],
    ],
  },
  {
    title: "Company",
    fields: [
      ["country", "Country"],
      ["address", "Address"],
      ["buyer_type", "Buyer Type"],
      ["categories", "Categories"],
      ["employee_size", "Employee Size"],
      ["org_scale", "Org Scale"],
      ["price_points", "Price Points"],
      ["store_count", "Store Count"],
    ],
  },
  {
    title: "Market Intelligence",
    fields: [
      ["brand_description", "Brand Description"],
      ["materials_dealt", "Materials Dealt"],
      ["customers_and_markets", "Customers & Markets"],
      ["revenue_turnover", "Revenue / Turnover"],
      ["competitors", "Competitors"],
      ["target_audience", "Target Audience"],
      ["import_countries", "Import Countries"],
      ["imports_from_india", "Imports From India"],
    ],
  },
  {
    title: "Social",
    fields: [
      ["linkedin_url", "LinkedIn"],
      ["linkedin_followers", "LinkedIn Followers"],
      ["instagram_handle", "Instagram"],
      ["instagram_followers", "Instagram Followers"],
      ["social_media_activity", "Social Activity"],
    ],
  },
  {
    title: "Engagement",
    fields: [
      ["first_contact_date", "First Contact"],
      ["last_contact_date", "Last Contact (Buyer)"],
      ["current_am", "Account Manager"],
      ["last_qalara_contact", "Last Qalara Contact"],
      ["last_email_subject", "Last Email Subject"],
      ["email_contact_summary", "Email Summary"],
    ],
  },
];

function val(v: unknown): string | null {
  const s = (v ?? "").toString().trim();
  return s === "" || s.toLowerCase() === "null" ? null : s;
}

export async function downloadLeadPdf(lead: Partial<Lead>): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  const width = pageW - margin * 2;
  const labelW = 140;
  let y = margin;

  const ensure = (h: number) => {
    if (y + h > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const org = (lead.organization || "Buyer profile").toString();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(20);
  doc.text(doc.splitTextToSize(org, width), margin, y);
  y += 22;

  const sub = [
    val(lead.country),
    val(lead.buyer_classification) ? `Priority: ${lead.buyer_classification}` : null,
    val(lead.website_confidence) ? `Web: ${lead.website_confidence}` : null,
  ]
    .filter(Boolean)
    .join("    •    ");
  if (sub) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(sub, margin, y);
    y += 14;
  }

  doc.setDrawColor(170);
  doc.line(margin, y, margin + width, y);
  y += 20;

  for (const g of GROUPS) {
    const rows = g.fields
      .map(([k, label]) => [label, val(lead[k])] as [string, string | null])
      .filter((r): r is [string, string] => r[1] !== null);
    if (!rows.length) continue;

    ensure(34);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(40);
    doc.text(g.title.toUpperCase(), margin, y);
    y += 6;
    doc.setDrawColor(220);
    doc.line(margin, y, margin + width, y);
    y += 16;

    doc.setFontSize(10);
    for (const [label, value] of rows) {
      const lines = doc.splitTextToSize(value, width - labelW);
      const blockH = Math.max(14, lines.length * 13);
      ensure(blockH + 4);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(90);
      doc.text(label, margin, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(20);
      doc.text(lines, margin + labelW, y);
      y += blockH + 6;
    }
    y += 10;
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    "Generated by Qalara Buyer Intelligence",
    margin,
    pageH - 24
  );

  const safe = org.replace(/[^a-z0-9]+/gi, "_").slice(0, 40) || "buyer";
  doc.save(`${safe}.pdf`);
}
